const express = require('express')
const { supplierUp } = require('../controllers/supplier controllers/supplier.signUp')
const { supplierLogin } = require('../controllers/supplier controllers/supplier.login')
const { getCategory } = require('../controllers/supplier controllers/supplier.getCategory')
const { addProduct } = require('../controllers/supplier controllers/add.product')
const { deleteProduct } = require('../controllers/supplier controllers/delete.product')
const { updateProduct } = require('../controllers/supplier controllers/update.product')
const { getAccount } = require('../controllers/supplier controllers/get.account')
const { addAcount } = require('../controllers/supplier controllers/add.account')
const { deleteAccount } = require('../controllers/supplier controllers/delete.account')
const { getOrder } = require('../controllers/supplier controllers/get.order')
const { updateOrderStatus } = require('../controllers/supplier controllers/update.status.order')
const { getPayment } = require('../controllers/supplier controllers/getPyment')
const { getOrderItem } = require('../controllers/supplier controllers/get.orderItem')
const { getProduct } = require('../controllers/supplier controllers/get.product')
const { supplierVerify } = require('../controllers/supplier controllers/supplier.verifay')
const { uplodeSupplierVerification } = require('../controllers/supplier controllers/uploding.detail.verification')
const { chekReviw } = require('../controllers/supplier controllers/is.reviw')
const { supplierData } = require('../controllers/supplier controllers/supplier.detail')
const { onlineStatus, offlineStatus } = require('../controllers/supplier controllers/isSupplier.online')
const { donePayment } = require('../controllers/supplier controllers/get.done.payment')
const { supplierProfile } = require('../controllers/supplier controllers/get.supplier.account')
const { editSupplierProfile } = require('../controllers/supplier controllers/edit.Supplier.profile')
const { getSupplierProfileImage } = require('../controllers/supplier controllers/get.supplier.image')




const router = express.Router()

router.post('/sign-up', supplierUp)
router.post('/login', supplierLogin)
router.post('/supplier-verifing', uplodeSupplierVerification)
router.post('/add-product', addProduct)
router.post('/add-account', addAcount)


router.put('/update-order-status/:id', updateOrderStatus)
router.put('/offline', offlineStatus)
router.put('/update-product/:id', updateProduct)
router.put('/online', onlineStatus)
router.put('/edit-profile', editSupplierProfile)

router.delete('/delete-product/:id', deleteProduct)
router.delete('/delete-account/:id', deleteAccount)


router.get('/get-account', getAccount)
router.get('/get-order', getOrder)
router.get('/get-category', getCategory)
router.get('/get-payment', getPayment)
router.get('/get-order-item/:id', getOrderItem)
router.get('/get-product', getProduct)
router.get('/is-verify', supplierVerify)
router.get('/chek-reviw', chekReviw)
router.get('/supplier-data/:id', supplierData)
router.get('/get-completed-payment', donePayment)
router.get('/get-supplier-profile', supplierProfile)
router.get('/supplier-profile', getSupplierProfileImage)
module.exports = router