const express = require('express')
const { supplierUp } = require('../controllers/supplier controllers/supplier.signUp')
const { supplierLogin } = require('../controllers/supplier controllers/supplier.login')
const { getCategory } = require('../controllers/supplier controllers/supplier.getCategory')
const { addProduct } = require('../controllers/supplier controllers/add.product')
const { deleteProduct } = require('../controllers/supplier controllers/delete.product')
const { updateProduct } = require('../controllers/supplier controllers/update.product')
const { getAccount } = require('../controllers/supplier controllers/get.account')
const { addAcount } = require('../controllers/supplier controllers/add.account')
const { deleteAccount } = require('../controllers/supplier controllers/delete.account')
const { getOrder } = require('../controllers/supplier controllers/get.order')
const { updateOrderStatus } = require('../controllers/supplier controllers/update.status.order')
const { getPament } = require('../controllers/supplier controllers/getPyment')
const { getOrderItem } = require('../controllers/supplier controllers/get.orderItem')
const { getProduct } = require('../controllers/supplier controllers/get.product')

const router = express.Router()

router.post('/sign-up' , supplierUp)
router.post('/login' , supplierLogin)
router.get('/get-category' , getCategory)
router.post('/add-product' , addProduct)
router.delete('/delete-product/:id' , deleteProduct)
router.put('/update-product/:id' , updateProduct)
router.get('/get-account' , getAccount)
router.post('/add-account' , addAcount)
router.delete('/delete-account/:id' , deleteAccount)
router.get('/get-order' , getOrder)
router.get('/update-order-status/:id' , updateOrderStatus)
router.get('/get-payment' , getPament)
router.get('/get-order-item/:id' , getOrderItem)
router.get('/get-product' , getProduct)
module.exports = router